# Site settings
title: a website made by tom
description: > # this means to ignore newlines until "baseurl:"
  Notes to self, quick experiments, sketches.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://made-by-tom.co.uk" # the base hostname & protocol for your site
twitter_username: tlrss
github_username: tomalrussell
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
