# Site settings
title: Tom Russell | Research Software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://made-by-tom.co.uk" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

collections:
  demos:
    output: true
    permalink: /demos/:path/
